#!/bin/sh -f

# Copyright (C) 2010, Guy Barrand. All rights reserved.
# See the file EsbRootView.license for terms.

bush_home=../../bush

. ${bush_home}/args

. ${bush_home}/ourex_header

#//////////////////////////////////////////////////////
#//////////////////////////////////////////////////////
#//////////////////////////////////////////////////////
#cppflags="${cppflags} -DINLIB_USE_CSZ"

#if [ ${build_visual} = "yes" ] ; then
#  cppflags="${cppflags} -I../applications"  # to bypass "read.icc" not found.
#fi

use_GLX=yes
use_X11=yes

use_exlib=yes
use_inlib=yes
use_freetype=yes
use_expat=yes
use_zlib=yes

. ${bush_home}/use/GLX
. ${bush_home}/use/X11

. ${bush_home}/use/exlib
. ${bush_home}/use/inlib
. ${bush_home}/use/freetype
. ${bush_home}/use/expat
. ${bush_home}/use/zlib

#//////////////////////////////////////////////////////
#//////////////////////////////////////////////////////
#//////////////////////////////////////////////////////

objs=
app_exe=plot_near_X11
app_src=../X11/plot_near.cpp

. ${bush_home}/application

. ${bush_home}/clean

